name: lepidoptera_sdms
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
 - R
 - r-base
 - r-terra
 - r-tidyterra
 - r-tidyverse
 - r-Hmisc
 - r-geometry
 - r-rootSolve
 - r-MESS
 - r-readr
 - r-lubridate
 - r-ggplot2
 - r-ggtext
 - r-mgcv
 - r-MASS
 - r-modeest
 - r-rnaturalearth
 - r-sf